config/routes.rb
Rails.application.routes.draw do
  root 'static#welcome'
  match '/auth/:provider/callback', to: 'sessions#github', via: [:get, :post]
  resources :users, only: [:create, :show, :index]
  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

  resources :projects do
    resources :issues
  end
  

  resources :tasks, except: [:new, :create, :update]
  get '/issues/:id/tasks/new', to: 'tasks#new', as: :new_task
  post '/issues/:id/tasks', to: 'tasks#create', as: :create_task
  patch '/issues/:id/tasks', to: 'tasks#update', as: :update_task

  resources :comments, except: [:new, :create, :update]
  get '/issues/:id/comments/new', to: 'comments#new', as: :new_comment
  post '/issues/:id/comments', to: 'comments#create', as: :create_comment
  patch '/issues/:id/comments', to: 'comments#update', as: :update_comment
end

app/models/issue.rb
class Issue < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  belongs_to :project
  has_many :tasks, dependent: :destroy
  has_many :users, through: :tasks
  has_many :comments, dependent: :destroy
end

app/controllers/issues_controller.rb
class IssuesController < SignedInController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]
  before_action only: [:edit, :update, :destroy] do
    redirect_if_not_authorized(@issue.project)
  end
  
  def index
    @issues = Issue.all
    set_project
  end

  def new
    @issue = Issue.new
  end

  def create
    set_project
    @issue = @project.issues.new(issue_params)
    if @issue.save
      redirect_to project_issues_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @issue.update(issue_params)
      redirect_to project_issue_path(@issue.project, @issue)
    else
      render :edit
    end
  end

  def destroy
    set_project
    @issue.destroy
    redirect_to project_path(@project)
  end

  private
  def issue_params
    params.require(:issue).permit(:title, :description)
  end

  def set_issue
    @issue = Issue.find_by(id: params[:id])
  end

  def set_project
    @project = Project.find_by(id: params[:project_id])
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_issue.html.erb
<p class="is-size-3"><%= link_to issue.title, project_issue_path(issue.project, issue) %></p>
<p class="is-size-4"><%= issue.description %></p>

app/views/issues/edit.html.erb
<%= form_with(model: @issue, url: project_issue_path, local: true) do |f| %>
  <%= render 'shared/errors', instance: @issue %>
  <div class="field">
    <%= f.label :title, class: "label" %>
    <%= f.text_field :title, class: "input" %>
  </div>

  <div class="field">
    <%= f.label :description, class: "label" %>
    <%= f.text_area :description, class: "input" %>
  </div>

  <%= f.submit class: "button is-link"%>
<% end %>

app/views/issues/index.html.erb
<h1 class="is-size-1"><%= link_to @project.title, project_path(@project) %></h1>
<p class="is-size-4"><%= @project.description %></p>
<% if @project.issues.any? %>
  <h2 class="is-size-2">Issues</h2>
  <% @project.issues.each do |i| %>
    <%= render partial: 'issues/issue', locals: { issue: i } %>
  <% end %>
<% else %>
  <h2 class="is-size-2"%>No Issues... Yet!</h2>
<% end %>
<%= link_to "Submit an Issue", new_project_issue_path(@project), class:"button is-success" %>

app/views/issues/new.html.erb
<%= form_with(model: @issue, url: project_issues_path, local: true) do |f| %>
  <%= render 'shared/errors', instance: @issue %>
  <div class="field">
    <%= f.label :title, class: "label" %>
    <%= f.text_field :title, class: "input" %>
  </div>

  <div class="field">
    <%= f.label :description, class: "label" %>
    <%= f.text_area :description, class: "input" %>
  </div>

  <%= f.submit class: "button is-link"%>
<% end %>

app/views/issues/show.html.erb
<h1 class="is-size-1"><%= @issue.title %></h1>
<p class="is-size-5"><%= @issue.description %></p>
<p class="is-size-5">Project: <%= link_to @issue.project.title, project_path(@issue.project) %></p>

<% if @issue.users.any? %>
  <h2 class="is-size-2">Currently Working on This Issue:</h2>
  <table class="table is-striped">
    <thead>
      <tr>
        <th>User</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% @issue.tasks.each do |t| %>
        <tr>
          <th><%= link_to t.user.username, t.user, class: "is-size-4" %></th>
          <th><%= link_to t.status, t, class: "is-size-4" %></th>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<% if signed_in? %>
  <%= link_to "Add Comment", new_comment_path, class:"button is-primary" %>
  <%= link_to "Add to Your Tasks", new_task_path, class:"button is-success" %>
  <% if authorized?(@issue.project) %>
    <%= link_to "Edit This Issue", edit_project_issue_path, class:"button is-link" %>
    <%= link_to "Delete This Issue", project_issue_path(@issue.project, @issue), method: :delete, class:"button is-danger" %>
  <% end %>
<% end %>

<% if @issue.comments.any? %>
  <h2 class='is-size-2'>Comments:</h2>
  <ul>
  <% @issue.comments.each do |c| %>
    <li class='is-size-4'><%= link_to "#{c.user.username} said: #{c.body}", comment_path(c) %></li>
  <% end %>
<% end %>