config/routes.rb
Rails.application.routes.draw do
  root 'static#welcome'
  match '/auth/:provider/callback', to: 'sessions#github', via: [:get, :post]
  resources :users, only: [:create, :show, :index]
  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

  resources :projects do
    resources :issues
  end
  

  resources :tasks, except: [:new, :create, :update]
  get '/issues/:id/tasks/new', to: 'tasks#new', as: :new_task
  post '/issues/:id/tasks', to: 'tasks#create', as: :create_task
  patch '/issues/:id/tasks', to: 'tasks#update', as: :update_task

  resources :comments, except: [:new, :create, :update]
  get '/issues/:id/comments/new', to: 'comments#new', as: :new_comment
  post '/issues/:id/comments', to: 'comments#create', as: :create_comment
  patch '/issues/:id/comments', to: 'comments#update', as: :update_comment
end

app/models/task.rb
class Task < ApplicationRecord
  validates :status, inclusion: { in: %w(in-progress finished) }
  
  belongs_to :user
  belongs_to :issue
end

app/controllers/tasks_controller.rb
class TasksController < SignedInController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action only: [:edit, :update, :destroy] do
    redirect_if_not_authorized(@task)
  end
  
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    set_issue
    @task = Task.new(task_params)
    @task.user = current_user
    @task.issue = @issue
    if @task.save
      redirect_to task_path @task
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to @task
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private
  def task_params
    params.require(:task).permit(:status)
  end

  def set_issue
    @issue = Issue.find_by(id: params[:id])
  end

  def set_task
    @task = Task.find_by(id: params[:id])
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: @task, url: create_task_path, local: true) do |f| %>
  <%= render 'shared/errors', instance: @task %>

  <div class="field">
    <%= f.label :status, class: "label" %>
    <%= f.select(:status, ['in-progress', 'finished'], class: "input") %>
  </div>

  <%= f.submit class: "button is-link" %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1 class="is-size-1">Your Tasks</h1>
<% if current_user.tasks.any? %>
  <table class="table is-striped">
    <thead>
      <tr>
        <th>Project</th>
        <th>Issue</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% current_user.tasks.each do |t| %>
        <tr>
          <th><%= link_to t.issue.project.title, project_path(t.issue.project) %></th>
          <th><%= link_to "#{t.issue.title}: #{t.issue.description}", project_issue_path(t.issue.project, t.issue) %></th>
          <th><%= link_to t.status, task_path(t) %></th>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="is-size-5">No tasks yet</p>
<% end %>

app/views/tasks/show.html.erb
<h1 class="is-size-1"><%= link_to "#{@task.user.username}'s", @task.user %> task: <%= link_to @task.issue.title, project_issue_path(@task.issue.project, @task.issue) %> for <%= link_to @task.issue.project.title, project_path(@task.issue.project) %><h1>
<p class="is-size-4"><%= @task.issue.description %></p>
<p class="is-size-4">Status: <%= @task.status %></p>
<% if signed_in? && authorized?(@task) %>
  <%= link_to "Edit This Task", edit_task_path, class:"button is-link" %>
  <%= link_to "Delete This Task", task_path(@task), method: :delete, class:"button is-danger" %>
<% end %>