config/routes.rb
Rails.application.routes.draw do
  root 'static#welcome'
  match '/auth/:provider/callback', to: 'sessions#github', via: [:get, :post]
  resources :users, only: [:create, :show, :index]
  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

  resources :projects do
    resources :issues
  end
  

  resources :tasks, except: [:new, :create, :update]
  get '/issues/:id/tasks/new', to: 'tasks#new', as: :new_task
  post '/issues/:id/tasks', to: 'tasks#create', as: :create_task
  patch '/issues/:id/tasks', to: 'tasks#update', as: :update_task

  resources :comments, except: [:new, :create, :update]
  get '/issues/:id/comments/new', to: 'comments#new', as: :new_comment
  post '/issues/:id/comments', to: 'comments#create', as: :create_comment
  patch '/issues/:id/comments', to: 'comments#update', as: :update_comment
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: true
  validates :category, presence: true
  belongs_to :user
  has_many :issues, dependent: :destroy

  scope :list_category, -> (category_search) { where("category LIKE ?", category_search) }
  def self.order_by_issue_count
    Project.left_joins(:issues).group(:id).order('COUNT(issues.id) DESC')
  end
end

app/controllers/projects_controller.rb
class ProjectsController < SignedInController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action only: [:edit, :update, :destroy] do
    redirect_if_not_authorized(@project)
  end
  
  def index
    if params[:q] && !params[:q].empty?
      @projects = Project.list_category(params[:q]).order_by_issue_count
    else
      @projects = Project.order_by_issue_count
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = current_user.projects.new(project_params)
    if @project.save
      redirect_to @project
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to @project
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private
  def project_params
    params.require(:project).permit(:title, :category, :description)
  end

  def set_project
    @project = Project.find_by(id: params[:id])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: @project, local: true) do |f| %>
  <%= render 'shared/errors', instance: @project %>
  <div class="field">
    <%= f.label :title, class: "label" %>
    <%= f.text_field :title, class: "input" %>
  </div>

  <div class="field">
    <%= f.label :category, class: "label" %>
    <%= f.text_field :category, class: "input" %>
  </div>

  <div class="field">
    <%= f.label :description, class: "label" %>
    <%= f.text_area :description, class: "input" %>
  </div>

  <%= f.submit class: "button is-link"%>
<% end %>

app/views/projects/index.html.erb
<h1 class="is-size-1">Projects</h1>
<div class="columns">
  <div class="column is-half">
    <%= form_tag(projects_path, method: :get, class: "field has-addons") do %>
    <%= text_field_tag(:q, params[:q], class: "input", placeholder: "Search Projects By Category") %>
    <%= submit_tag("Search", class: "button is-info") %>
    <% end %>
  </div>
</div>
<% if !@projects.empty? %>
  <table class="table is-striped">
    <thead>
      <tr>
        <th>Project</th>
        <th>Description</th>
        <th>Category</th>
        <th>Creator</th>
        <th># of Issues</th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |p| %>
      <tr>
        <th><%= link_to p.title, p %></th>
        <th><%= p.description %></th>
        <th><%= p.category %></th>
        <th><%= link_to p.user.username, p.user %></th>
        <th><%= p.issues.count %></th>
      </tr>
        <% end %>
    </tbody>
  </table>
<% else %>
  <div class="container mb-5">
    <p class="is-size-4 has-text-danger">No projects found</p>
  </div>
<% end %>
<%= link_to "Create New Project", new_project_path, class:"button is-success" %>

app/views/projects/show.html.erb
<h1 class="is-size-1"><%= @project.title %></h1>
<p class="is-size-4"><%= @project.category %></p>
<p class="is-size-5"><%= @project.description %></p>
<% if @project.issues.any? %>
  <h2 class="is-size-2">Issues</h2>
  <% @project.issues.each do |i| %>
    <%= render partial: 'issues/issue', locals: { issue: i } %>
  <% end %>
<% else %>
  <h2 class="is-size-2"%>No Issues... Yet!</h2>
<% end %>
<% if signed_in? %>
  <%= link_to "Submit an Issue", new_project_issue_path(@project), class:"button is-success" %>
  <% if authorized?(@project) %>
    <%= link_to "Edit This Project", edit_project_path, class:"button is-link" %>
    <%= link_to "Delete This Project", project_path(@project), method: :delete, class:"button is-danger" %>
  <% end %>
<% end %>