config/routes.rb
Rails.application.routes.draw do
  root 'static#welcome'
  match '/auth/:provider/callback', to: 'sessions#github', via: [:get, :post]
  resources :users, only: [:create, :show, :index]
  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

  resources :projects do
    resources :issues
  end
  

  resources :tasks, except: [:new, :create, :update]
  get '/issues/:id/tasks/new', to: 'tasks#new', as: :new_task
  post '/issues/:id/tasks', to: 'tasks#create', as: :create_task
  patch '/issues/:id/tasks', to: 'tasks#update', as: :update_task

  resources :comments, except: [:new, :create, :update]
  get '/issues/:id/comments/new', to: 'comments#new', as: :new_comment
  post '/issues/:id/comments', to: 'comments#create', as: :create_comment
  patch '/issues/:id/comments', to: 'comments#update', as: :update_comment
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :issue
end

app/models/issue.rb
class Issue < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  belongs_to :project
  has_many :tasks, dependent: :destroy
  has_many :users, through: :tasks
  has_many :comments, dependent: :destroy
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: true
  validates :category, presence: true
  belongs_to :user
  has_many :issues, dependent: :destroy

  scope :list_category, -> (category_search) { where("category LIKE ?", category_search) }
  def self.order_by_issue_count
    Project.left_joins(:issues).group(:id).order('COUNT(issues.id) DESC')
  end
end

app/models/task.rb
class Task < ApplicationRecord
  validates :status, inclusion: { in: %w(in-progress finished) }
  
  belongs_to :user
  belongs_to :issue
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, uniqueness: true
  validates :username, presence: true
  has_many :projects
  has_many :tasks
  has_many :issues, through: :tasks
  has_many :comments

  def self.find_or_create_with_oauth(auth)
    user = User.find_or_create_by(uid: auth["uid"]) do |u|
      u.username = auth["extra"]["raw_info"]["login"]
      u.password = SecureRandom.hex(20)
    end
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < SignedInController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action only: [:edit, :update, :destroy] do
    redirect_if_not_authorized(@comment)
  end
  
  def index
    @comments = Comment.all
  end

  def new
    @comment = Comment.new
  end

  def create
    set_issue
    @comment = @issue.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to project_issue_path @issue.project, @comment.issue
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to project_issue_path @comment.issue.project, @comment.issue
    else
      render :edit
    end
  end

  def destroy
    @issue = @comment.issue
    @comment.destroy
    redirect_to project_issue_path(@issue.project, @issue)
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_comment
    @comment = Comment.find_by(id: params[:id])
  end

  def set_issue
    @issue = Issue.find_by(id: params[:id])
    puts "PARAMS[:ID] == #{params[:id]}"
  end
end

app/controllers/issues_controller.rb
class IssuesController < SignedInController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]
  before_action only: [:edit, :update, :destroy] do
    redirect_if_not_authorized(@issue.project)
  end
  
  def index
    @issues = Issue.all
    set_project
  end

  def new
    @issue = Issue.new
  end

  def create
    set_project
    @issue = @project.issues.new(issue_params)
    if @issue.save
      redirect_to project_issues_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @issue.update(issue_params)
      redirect_to project_issue_path(@issue.project, @issue)
    else
      render :edit
    end
  end

  def destroy
    set_project
    @issue.destroy
    redirect_to project_path(@project)
  end

  private
  def issue_params
    params.require(:issue).permit(:title, :description)
  end

  def set_issue
    @issue = Issue.find_by(id: params[:id])
  end

  def set_project
    @project = Project.find_by(id: params[:project_id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < SignedInController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action only: [:edit, :update, :destroy] do
    redirect_if_not_authorized(@project)
  end
  
  def index
    if params[:q] && !params[:q].empty?
      @projects = Project.list_category(params[:q]).order_by_issue_count
    else
      @projects = Project.order_by_issue_count
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = current_user.projects.new(project_params)
    if @project.save
      redirect_to @project
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to @project
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private
  def project_params
    params.require(:project).permit(:title, :category, :description)
  end

  def set_project
    @project = Project.find_by(id: params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def github
    user = User.find_or_create_with_oauth(auth)
    if user
      session[:user_id] = user.id
      redirect_to user
    else
      @error = "Username already set up manually"
      render :new
    end
  end
  
  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      @error = "Incorrect username and/or password"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to signin_path
  end

  private
  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def welcome
  end
end

app/controllers/tasks_controller.rb
class TasksController < SignedInController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action only: [:edit, :update, :destroy] do
    redirect_if_not_authorized(@task)
  end
  
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    set_issue
    @task = Task.new(task_params)
    @task.user = current_user
    @task.issue = @issue
    if @task.save
      redirect_to task_path @task
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to @task
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private
  def task_params
    params.require(:task).permit(:status)
  end

  def set_issue
    @issue = Issue.find_by(id: params[:id])
  end

  def set_task
    @task = Task.find_by(id: params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    set_user
  end

  private
  def set_user
    @user = User.find_by(id: params[:id])
  end
  
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forge And Fix</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="icon" href="/hammer-and-wrench.svg">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.0/css/bulma.min.css" integrity="sha512-ADrqa2PY1TZtb/MoLZIZu/Z/LlPaWQeDMBV73EMwjGam43/JJ5fqW38Rq8LJOVGCDfrJeOMS3Q/wRUVzW5DkjQ==" crossorigin="anonymous" />
  </head>

  <body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
	<a class="navbar-item" href="/">
	  <img src="/hammer-and-wrench.svg" alt="Projects" width="112" height="28"></a>
    <%= link_to "All Projects", projects_path, class: "navbar-item" %>
    <%= link_to "Creators", users_path, class: "navbar-item" %>
      </div>
      <%if !signed_in? %>
      <div class="navbar-end">
	<div class="navbar-item">
	  <div class="field is-grouped">
	    <p class="control">
	      <%= link_to "Sign In With GitHub", '/auth/github', method: :post, class:"button is-link" %>
	    </p>
	    <p class="control">
	      <%= link_to "Sign Up", signup_path, class: "button is-success" %>
	    </p>
	    <p class="control">
	      <%= link_to "Sign In", signin_path, class: "button" %>
	    </p>
	  </div>
	</div>
      </div>
      <% else %>
      <div class="navbar-start">
	<%= link_to "My Tasks", tasks_path, class: "navbar-item" %>
	<%= link_to "My Projects", user_path(current_user), class: "navbar-item" %>
      </div>
      <div class="navbar-end">
	<%= link_to "Sign Out", signout_path, method: :delete, class: "navbar-item" %>
      </div>
      <% end %>
      
</div>
</nav>
    <div class="container has-text-justified">
      <%= yield %>    
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if instance.errors.any? %>
  <div class="has-text-danger">
    <h2><%= pluralize(instance.errors.count, "error") %> prohibited this <%= instance.class.name.downcase %> from being saved:</h2>
    <ul class="fields_with_errors">
      <% instance.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>